### ISSUE TITLE
Questions about this new project - Thorium v.xxx.xxx.xxx

### ISSUE THREAD

**Issue by Rusenche** [Alex313031/Thorium-Win#1]
I see that this project is still new and is something like an alpha version, but a few questions:

1. This Thorium project is something like Ungoogled Chromium?!
I read the information about Thorium, but I'm not entirely sure if it's protected like Ungoogled Chroium ?! Please for further clarification. /Or is it a project - like RobRich999?!/

2. About Floc - I didn't find anything - is it enabled by default or is it disabled ?!

Thanks for the answers.

For me, question 1 is very important and whether Thorium is like Ungoogled Chromium. According to me, having a translator on the pages means to me that Thorium is not protected like Ungoogled Chromium, but is something like RobRich's builds.

I transferred my entire account. Passwords were not transferred. Strange. I have to add them manually. Good thing you offer a portable version. So far so good.

According to https://amifloced.org/ -> Your browser does not currently have FloC enabled.

As if a little more memory is used?!

**Comment by Alex313031** [comment]
These are windows builds of https://github.com/Alex313031/Thorium which is for linux. In both, the "EXPERIMENTAL FEATURES/DIFFERENCES BETWEEN CHROMIUM AND THORIUM" section describes differences. The patches from debian will not be applicable to windows. It has some patches from ungoogled chromium, and has compiler optimizations from robrich as well as my own (added cflags = -03 and FMA support, almost all CPUS supporting AVX will also support FMA). I have not modified anything related to FLOC, as it is an origin trial right now, with only 0.5 percent of chromium browsers having it on. After release 100 I will be most likely disabling FLOC, but I don't want to right now because it won't affect most users, and I want it to be done in the upstream project so I don't constantly have to monitor and possibly change alot of code to disable it for every release. If you use linux, I would recommend using thorium there. I offer it as a .deb, but you could easily make it portable. For instructions on that you can ask me here or there.

**Comment by Rusenche** [comment]
@Alex313031

For FLOC, I learned that you will turn it off at a later stage, although even now it can be seen that it was turned off according to my test in the first comment in this new topic.

When I wrote my first comment in this new topic - I read readme.md. As far as I understand, various fragments of ungoogled chromium, bromite and vanadium were taken.

I am using Windows 7 x64. I prefer only portable versions.


But I didn't understand this: Should it be understood that Thorium is as secure/confidential as Ungoogled chromium or not?!


Regarding the use of more RAM - in my initial observation it was so - compared to my other portable version of Ungoogled chromium v.95.0.4638.69 - at the moment 7 days ago, because there is already Ungoogled chromium v.96.0.4664.45.

**Comment by Alex313031** [comment]
@Rusenche Yay! a fellow win 7 user. I octuple boot XP, 7, 10, 11, debian, arch, ubuntu, and chromiumos. It is NOT as secure as ungoogled chromium, but on purpose. I dont want to hinder thorium by removing google services or cookie features or prefetching, however I cherry picked what I felt was the most important patches. Upon further thought, I have decided I WILL be removing FLOC though. It will land in thorium first, and thorium-win whenever I build for windows again which should be soon. Actually working on it now as we speak.

**Comment by AXKuhta** [comment]
Wanted to chip in and say that https://github.com/Alex313031/Thorium-Win/releases/tag/M99.0.4765.0 seems to run fine on a SandyBridge device. Even if the compiler was told to generate FMA instructions, it seemingly didn't generate any.

**Comment by Rusenche** [comment]
Hello

I apologize for answering so late.

I've been transferring all settings to Ungoogled chromium for a few weeks now. But ... I tested Thorium v.99.0.4785.0. I transferred all settings successfully. Even my passwords have already been transferred

successfully. Which makes me happy. Everything works smoothly and well. I even added WidevineCdm and it worked successfully.

Flash player works, and that surprised me positively. At least for me, Flash player doesn't work with Ungoogled chromium.

1. Will the Thorium project be long-term?

2. Can you do how to say it - not a special version, but a version that is currently stable -> v.96.0.4664.110 for x86 and x64 portable again?

I mean the Thorium project should focus on stable versions of Chromium.

Update for Thorium v.99.0.4785.0 -> When starting from the "RUNNER" folder of "THORIUM.bat" - Windows 7 x64 pulls out a window that "thorium.exe" cannot be found - apparently there is an error in "bat" file?

3. I noticed that the following two flags were missing:
- chrome: // flags / # close-window-with-last-tab
- chrome: // flags / # close-confirmation

Is it possible to restore them?

4. I checked Floc - it doesn't work, which is good. Will you disable / remove it in your configurations in the future?

5. Is it possible in your portable versions when using Torium - all files that are created to be created only in your own folder and not in "\AppData\Local\Chromium" - just to be in your future configurations ?! Because for this version to be portable, everything must be in its own folder, not have files somewhere in "\AppData\Local\Chromium".

6. The translator in the pages has already been removed. Forever?

7. You wrote that you do not want to remove google services. But google translate in the first version was available, and in the current Thorium v.99.0.4785.0 - no longer available. I mean, Thorium is supposedly less secure than Ungoogled chromium, but the google translate service is still removed? Forever?

8. In my opinion - in these times when data transmission is a mass phenomenon, it is better to consider the possibility of Thorium being as secure as Ungoogled chromium.

Consumers are looking for privacy because companies are robbing us and spying on us. We have all witnessed our mailboxes being filled with spam because they use our data. According to me consider Thorium to be = Ungoogled chromium as a secure browser.

9. For comparison - https://github.com/macchrome/winchrome/releases/tag/v96.0.4664.110-r929512-Win64 - 75,1 MB. And why is Thorium v.99.0.4785.0 - 199 MB ?!

10 ... Keep going boldly. You have started a great project and it is good.

But I would like to use only stable versions and I would like to make a portable version - v.96.0.4664.110. ;)

**Comment by Alex313031** [comment]
@Rusenche Hey, sorry on MY part for getting back so late. SO lemme answer in order.
1. Yes it will be long term. I use Thorium as my day to day browser, and will continue work on it for the foreseeable future.
2. One of the founding things I wanted with Thorium was for it to always be built to tip-o-tree. The source code is rebased by me quite often on upstream, and making a "stable" release would mean having to backtrack, and probably make another repo for that and maintain a whole duplicate list of files with different contents. Thorium is sometimes unstable, but I test my releases before I release them, and its usually not something too breaking if it does break.
3. That was a change made upstream. And yes it was an error on my part, I forgot to rename chrome.exe in that release, you can manually change it in the .bat but read below as you'll probably want the latest release.
4. FLOC is now completely disabled by default in all builds of Thorium for all platforms.
5. The Thorium portables for both linux and win now properly set the user data folder to a folder inside wherever you unpacked it too. Sorry if that caused issues.
6. The translator is related to missing Google API keys. However, all builds of thorium for all platforms now have baked in API keys, so google sync and translate and maps will work correctly now.
7. Yes I do not want to remove google services, see No. 6 on why it wasn't working before.
8. I am going to add more patches from ungoogled chromium, but to make it as secure as ungoogled chromium would hinder alot of features, not to mention constantly having to do three way merges on hundreds of files with the ungoogled repo, my repo, and upstream.
9. This is because of all the compiler optimizations I have added. I basically optimized as much as one can possibly do, at the expense of binary bloat, but overall the application doesn't take up much space, and I'd rather have the 2-8% performance improvement over saving ~200mb data (when unpacked)
10. Thank you

Also, Thorium has widevine. You do not (and shouldn't) manually move the widevinecdm folder from another chromium installation. Instead, if it is not working, go to chrome://components and update all the components (including widevine) and it should work for you. I would recommend closing thorium, deleting the contents of the widevinecdm folder you moved over, then do the above to re-download the widevine cdm using the built in Thorium component updater.

**Comment by Alex313031** [comment]
@AXKuhta Yeah that release actually didn't have FMA, but I didn't update it to reflect that.
Doesn't matter now, because thorium is now compiled with AVX and AES, omitting the FMA flag (I used that back when I was on a piledriver system (2ng gen AMD FX), but realized it prevented alot of people from running it.) I now have a 4790K so i make personal builds with -march=haswell and -mtune=haswell, but all public releases are as I said above. It should work on any CPU sandy bridge (2nd gen core) or Bulldozer (1st gen AMD FX) or later.

**Comment by Alex313031** [comment]
@Rusenche Are you there m8? I replied above ^.
