### ISSUE TITLE
Any way to remove Google hangout and PDF extensions?

### ISSUE THREAD

**Issue by necros2k7** [Alex313031/Thorium-Win#18]
subj

**Comment by Alex313031** [comment]
@necros2k7 No. These are built in and enabled for all Chromium releases. The only reason you see them on chrome://extensions is because I added a patch to show ALL extensions, including internal ones, not just ones the user adds from the web store. It is nothing to worry about. You could have to remove these in source code, and if you did so, the web store, viewing pdfs, and google hangouts would all be broken

**Comment by necros2k7** [comment]
So maybe it`s better to do not shot `em if we have no control over them?)

**Comment by Aedon** [comment]
Thank god i found this thread, I was getting worried seeing an un-deletable extension that could see my history and capture screen.
