### ISSUE TITLE
Option to put Cache into Memory

### ISSUE THREAD

**Issue by Sa-Ja-Di** [Alex313031/Thorium-Win#54]
Not sure if that is even a possibility, but Chromium's ultimate weakness and why it is so devastating for SSD's is that it constantly writes to the disk as crazy.

So i wonder if there is some possibility to implement something which mitigates this constant writings like for example adding an option to push cache into memory?

**Comment by gz83** [comment]
I don't think this change should be made at this stage

@Sa-Ja-Di

**Comment by RobRich999** [comment]
There is another alternative. Have an extra M.2 slot? If not, have an open PCI-E slot for a cheap M.2 adapter card? Consider adding a small Optane SSD for browser caches, app caches, temp files, etc.

You can get new (usually system pull) Optane 16GB SSD for under $10 on eBay. Around $25 for the 32GB model. Yeah, Optane is discontinued, but it is highly resilient to drive writes. The Optane 16/32GB drives are rated for 182.5TB drive write endurance.

**Comment by Girofox** [comment]
There is an easy option to completely disable disk caching, just add the following flag to THORIUM.BAT:
`--disk-cache-dir=nul`
Under Windows Resource Monitor you can see that there isn't any write activity to cache more. The memory cache still works of course, refreshing any webpage is still fast, in my case even faster because of unnecessary disk activity.

What i did additionally to reduce disk activity is setting the following file as read-only in `..\USER_DATA\Default` folder:
`Network Action Predictor`

If you don't want to mess with anything of this just launch a new **incognito window**, then there is no caching at all and no session store or history disk writes.

**Comment by trimechee** [comment]
@Girofox Really we can disable session store in incognito mode? this is huge news, it's a nightmare to disable session sore in chromium, I tried so many flags but these flags were deprecated, on firefox I was able to completely disable sesson store, please did you check with the task manager that no store session data is recorded when using incongnito mode ?

**Comment by trimechee** [comment]
Thank you for testing @Girofox  :) Sadly it seems there is session storage even in incognito mode :( : 




i have tested many flags and search in peter .sh site....it seems impossible to disable session store, perhaps with the performance options which freeze inactive tabs and reduce background tasks, that improves things and minimizes session store, that's why I asked our beloved Thorium browser to add this option even plugged....


"Android and chrome I believe allow you to access old keys in session storage, but not write to it. I know that Safari will not allow any use of session or local storage."

"Chrome will support localStorage and sessionStorage in private window."


https://stackoverflow.com/questions/18860098/on-a-browser-sessionstorage-in-safaris-private-browsing-does-not-work-the-same

"Safari will just use a quota of 0 in private mode, so all attempts to set a value will fail. This is kinda OK according to the [spec](http://dev.w3.org/html5/webstorage/#disk-space), as the spec does not mandate a minimum space requirement.
Chrome and Firefox still allow you to use storage, however private storage is independent from non-private, i.e. setting an item in private mode will not reflect back into non-private mode (important for localStorage only)."

https://stackoverflow.com/questions/26042423/web-storage-sessionstorage-and-localstorage-in-private-browsing-mode-incognit

**Comment by Girofox** [comment]
Glad i can help!
This is a screenshot of the disk writes relatively early when opening some tabs and interacting with them. I used System Informer because it can filter by name:

![image](https://github.com/Alex313031/Thorium-Win/assets/43116061/6c86ef8f-4fdb-4eab-aa29-56a766033188)

So far you can see `Safe Browsing` feature via Google sometimes writes to disk but only at the beginning. Can be disabled though. Most writes in **incognito mode** are Extensions like uBlock, Tampermonkey or Stylus which i did enable for use in incognito mode, they write in some log files and databases, but only at beginning too. Don't know what these weird .tmp files are but these are related to `network process` in Chromium.

After some idle time the disk writes are almost zero, even when interacting and loading another new tabs:

![image](https://github.com/Alex313031/Thorium-Win/assets/43116061/5632c83f-51f9-4956-8d27-9d3bc00718c2)

**Comment by BYTEMEE1** [comment]
> @gz83 @Sa-Ja-Di He is right, but this is not Thorium specific. Every browser, including Firefox and WebKit based browsers, write a whole bunch of little files, and constantly rewrites them. This can be slow on hard drives, and it is bad for SSDs.
> 
> While I don't want to integrate this by default, what you can do is set up a ram disk and then use the
> 
> `--disk-cache-dir=/path/to/ramdrive` and `--disk-cache-size=sizeofcacheinbytes` For example 1GB would be 10240445137
> 
Can you explain this command to relocated browser cache to a ramdrive a little more clearly? Are the commands run simultaneously like this:

```
thorium.exe -disk-cache-dir=V:\Ramdrive --disk-cache-size=10240445137

or sequentially, one after the other? Also wouldn't 1GB be  1073741824 in bytes?
```

**Comment by Alex313031** [comment]
@trimechee @BYTEMEE1 @gz83 @Sa-Ja-Di @Girofox Yeah, you can do this yourself. I could add a flag to Thorium, but most people wouldn't use it, and I would have to hard set it to a ramdrive letter like "R:\". If a user was to have the ramdrive somewhere else, it wouldn't work. So, I won't be adding this. See above comments for solutions. It can't be set to write directly to RAM, it must be a RAM-drive since it expects cache contents to be on a normal block addressable device.

**Comment by Girofox** [comment]
> @trimechee @BYTEMEE1 @gz83 @Sa-Ja-Di @Girofox Yeah, you can do this yourself. I could add a flag to Thorium, but most people wouldn't use it, and I would have to hard set it to a ramdrive letter like "R:". If a user was to have the ramdrive somewhere else, it wouldn't work. So, I won't be adding this. See above comments for solutions. It can't be set to write directly to RAM, it must be a RAM-drive since it expects cache contents to be on a normal block addressable device.

I agree, in Linux it is much easier because the flag "--cache-dir=/dev/null" definitely works universally and so the cache is completely disabled. On Windows this would just create an folder dev null in user data directory, so i made an ramdisk with mounting point and then removed the ramdisk via imdisk. So i can always point to that dead mount point via flags.
