### ISSUE TITLE
Launch batch file broken

### ISSUE THREAD

**Issue by K4sum1** [Alex313031/Thorium-Win#6]
![ScreenShot_20220209155003](https://user-images.githubusercontent.com/77039240/153296275-70fe3ae7-77d5-4a51-a47f-023875942409.png)

**Comment by Alex313031** [comment]
@K4sum1 Ahhhh nice to see a fellow windows 7 user! You gotta run it from within the folder. You can just double click the .bat. Or open a cmd window in the folder you extracted it in and run thorium.bat

**Comment by K4sum1** [comment]
It does the same when double clicking the .bat, it's just I couldn't move or resize the window when double clicking so I opened it in CMD for the image.

**Comment by Alex313031** [comment]
@K4sum1 You're right! Excuse me but I need to update my repo and take down and reupload that zip! Just edit them and remove one of the dots after start /d
for example "..\bin\" to ".\bin\"

**Comment by Alex313031** [comment]
@K4sum1 Had to test in a VM just to make sure, and then realize this is a batch file not a linux .sh script. Im used to linux where two dots means "the parent directory" versus win which uses one dot. Thanks for filing this issue or I would have never caught this simple error! 
Also, how are you liking Thorium, or is this your first time using it?

**Comment by Alex313031** [comment]
@K4sum1 Oh, you're using the M54 release thats the newest chromium to work with XP? They took that down sadly, but you can still get it from the web archive easily. And I agree but dont you mean chromium 49? 
I like firefox and forks (besides pale moon and kmelon) as well, but use thorium as my daily driver.

So is it working for you now?

Also, do you use XP at all? I like old and new oses, and have machines as old as a 386 PS/2 with dos and win 3.11, through to 95-pentium 2, nt 4.0-celeron, 98se-pentium3, 2000-pentium4, xp-fx-8370, and 7, 10, and 11 As well as a lot of linux distros and ChromiumOS (i got my own builds of that too in my repo) on my main i7 4790K machine.

Lastly, do you use win 7 or 8 more? Do you use linux at all? And what are your system specs?

**Comment by K4sum1** [comment]
> @K4sum1 Oh, you're using the M54 release thats the newest chromium to work with XP? They took that down sadly, but you can still get it from the web archive easily. And I agree but dont you mean chromium 49? I like firefox and forks (besides pale moon and kmelon) as well, but use thorium as my daily driver.
Chromium 49 works too, however 49 has a material design incognito screen, while 48 is the old style.

> So is it working for you now?
The script works after the edit.

> Also, do you use XP at all?
Making a custom version of Windows Server 2003, been trying to install it on my laptop, one of the modded drivers might not like it.

> Lastly, do you use win 7 or 8 more? Do you use linux at all? And what are your system specs?
I use 7 more, but I do like 8. I swap between 7, 8.0, and 8.1 every so often.
My system is a Ryzen 7 2700X with a GTX 970 and 48GB of RAM.

**Comment by K4sum1** [comment]
> @K4sum1 Wait you use 8.0? Why? It cant even get updates, just like 7RTM with no SP1. And most of the small changes between 8 and 8.1 are good ones.

8.0 can use Server 2012 R1 updates. Also it's lighter, easier to debloat, and faster than 8.1. Also fun fact, most of what you consider 8.1 is from the updates it got. Booting straight to desktop, desktop apps set as default, search and power icons on the start screen, metro apps having title bars, metro apps on taskbar, etc weren't in RTM 8.1.

Once you install Classic Shell or whatever, 8.0 is basically a faster 8.1 with libraries enabled by default. Except paint.net devs are cunts and limit 8.0 to version 4.0.19.

> And that's cool. Is it 32 bit 2003 or 64? What driver did you mod? And whats custom about it?

Using 32 bit for now, but I'll likely use 64 bit when the update pack comes out. I didn't mod the drivers, and it's a few drivers. I have a modded ACPI, modded USB drivers that work with PAE, and modded SATA drivers that work with even the newest Intel chipsets.

> That's nice. I got a i7 4790K OC'd to 4.6Ghz. on a Z97 board, GTX 970, 24GB DDR3 1866Mhz. Do you use that patch to allow updates on <win10 for kaby lake/ryzen and higher?

I use the patch if I use my copy of Windows 7 or Windows 8 that is updated to 2020-01. I don't go further for any OS due to telemetry being in future updates. I'm currently running 7 updated to 2016-09, so I don't need the patch currently. Even though I don't intend to install any updates and even disable the update service, I still apply the patch so I don't get those annoying popups.

> Sadly, intel 11th gen and higher and ryzen 5000 and higher (im assuming) don't work at all with windows 7, and even if you could get it booted, there arent drivers (even modded ones) for alot of the stuff on z5xxx or X570 boards.

They work, Ryzen is easier to set up than Intel, and I have set up a Ryzen 5800X with B550 to work with both 7 and 8. I intend to get a 5800X or maybe even a 5800X3D and stick with it for the foreseeable future. Only reason I want to upgrade from my 2700X is to do some PS3 emulation. Might as well get the best of AM4 to use 7 and avoid Pluton.

**Comment by Alex313031** [comment]
I assumed on ryzen 5000, but after looking it up more I saw people that got it to work. Thats cool that it works! Are there any things you couldn't get drivers for? I know the latest official chipset drivers from amd dont support 7. And so youre saying win 7 also works on 11th/12th gen intel??? That im pretty sure of (havent tested myself cuz i dont have the money lol) because all i've found online is people citing failure when trying to get win 7 to work on 11th gen+

So what platform are you using 2003 on and what are you using it for?

And dude why go that old (2016) on 7 just to not get telemetry. Thats like pretty unsecure. Even with telemetry, its way less than say win 10 or 11, and doesn't contain any personal identifiable information. My win 7 has all updates up till the very last 2020 one, as well as some hotfixes and the Windows Management Framework update that wasn't offered through windows update strangely, but can be found by just searching the microsoft website..

**Comment by Alex313031** [comment]
@K4sum1 Thats interesting. And lol "just because you can" thats exactly why I still run XP. XP was my daily driver OS until 2018. 7 was my daily driver until 2020. I use crunchbangplusplus linux as daily driver now. But whenever I use windows its usually 7, unless a program requires 10.

And IDK mate maybe this is just a to each his own thing, but I feel more comfortable running a fully up to date 7. Now if we are talking win 10 or 11, I've purposefully not updated in the past and I can see some more use there with not using all the updates.

Oh and idk if I asked this already, but do you use linux at all?

**Comment by K4sum1** [comment]
> Oh and idk if I asked this already, but do you use linux at all?

Sometimes, but I dunno when or if I'll next try maining it.

**Comment by Alex313031** [comment]
@K4sum1 What distro do you use?

Also, I think I have the icon issue fixed. Compiling now to verify, but Thorium should display the right icon in the taskbar now

**Comment by K4sum1** [comment]
> @K4sum1 What distro do you use?

I like Arch because of the AUR, but I want everything necessary to be in the distro. I settled on Manjaro Mate minimal, which after installing, I remove packages I don't need.

**Comment by Alex313031** [comment]
@Alex313031 Noice. If you like arch, and something minimal but with sane defaults, might I recommend the arch distro I use archlabs > [https://archlabslinux.com/](url)

Uses openbox, but has alot of stuff configured already and has GUI configurators for stuff, so it takes out of the main complaint of "takes too much manual text file/xml configuration" people have about the otherwise great WM
