### ISSUE TITLE
installer seems buggy

### ISSUE THREAD

**Issue by Unixware** [Alex313031/Thorium-Win#67]
**System Details**
 - OS: [Windows 11]
 - Thorium Version 

**Problem**
mini installer does run, asks permission , then ... quits 

**Additional Notes**
No way to be installed on Win11 , laptop with Intel Celeron N4120 (quad core) , this is a Q4 2019 CPU

**Comment by Unixware** [comment]
ok I figure it out, is not even compatible with 11...

**Comment by gz83** [comment]
Thanks for raising this issue.

But what I need to tell you is that what you understand is not correct. The current system support of Thorium browser is consistent with that of Chroium/Chrome.

The reason the version in the Thorium-Win repo won't work on your computer is because your processor doesn't support the AVX instruction set, and the version in that repo is built using the AVX instruction set.

If you want to use the Thorium browser on your computer, you need to use the SSE3 version

https://github.com/Alex313031/Thorium-Special/releases/tag/M116.0.5845.169

@Unixware

**Comment by Alex313031** [comment]
@Unixware Yeah, Thorium supports Windows 11 just fine. It is your CPU that is not compatible. Chromium/Chrome are compiled with SSE3, for compatibility. Thorium is compiled with AVX for performance. However, not every CPU supports this. CPUs newer than 2nd Gen Core support it, EXCEPT sometimes lower end Pentium or Celeron CPUs will omit AVX support, even though the underlying architecture does. This is what your case is. Even though your CPU is "Gemini Lake" which is the mobile version of 8th Gen Core, it doesn't have AVX. 

You can use the SSE3 version though. That is what the Thorium-Special repo is for: SSE3 Linux and Windows releases.

**Comment by Unixware** [comment]
oh crap, thanks! I did not search well the github and found only the AVX and the 'plain' one installer, darn, had the feeling the CPU supprted AVX as was a fairly recent model.. #facepalm  the SSE3 one works like a charm :)
