### ISSUE TITLE
the installer crash

### ISSUE THREAD

**Issue by tamajon** [Alex313031/Thorium-Win#7]
good morning, when I try to install thorium the installer stops for no reason and the installation fails

**Comment by Alex313031** [comment]
@tamajon What release are you using? What OS are you using? What CPU do you have?

**Comment by tamajon** [comment]
the portable version worked fine
8th Release - M100.0.4865.0 AVX2
windows 8.1 x64
celeron 847

**Comment by Alex313031** [comment]
@tamajon hmmmm thats strange. That release is an AVX2 release, but your celeron only supports AVX. I would have said this is why it didn't work. But if the portable version works, I guess thats good. But it also means that for some reason that build is not using AVX2 instructions.
In any case, next release will be a normal AVX release, and hopefully I will have worked out the icon bug. Have you experienced this, where the icon on the taskbar is a yellow "warning icon" rather than the correct Thoirum logo?

**Comment by tamajon** [comment]
In the portable version that I was able to run I had no problems with the icon, it was fine. Now I will try to install the new version, thanks for your effort

**Comment by paulatreides-web** [comment]
thorium 10th Release - M101.0.4918.0 crash for me
intel core i5 tiger-lake U (with AVX2 and AVX512)
windows 11
(but thorium 9th Release - M100.0.4888 work fine)

**Comment by Alex313031** [comment]
Try the latest AVX2 release. Rince robrich has stopped making chromium releases, I have committed to make windows avx and avx2 releases, and made a new repo for the avx2 releases. https://github.com/Alex313031/Thorium-AVX2/

Try the latest release in there.

**Comment by tamajon** [comment]
thorium 10th Release - M101.0.4918.0, installer crash
Windows 8.1 x64
Celeron 847 (with AVX)

**Comment by Alex313031** [comment]
@tamajon @paulatreides-web How is it now with the latest releases?

**Comment by Alex313031** [comment]
@paulatreides-web hows it comin?

@tamajon Correction, some celerons and pentiums below skylake DO have SSE4.2, but still no AVX.
If you dont believe me, see here https://ark.intel.com/content/www/us/en/ark/products/56056/intel-celeron-processor-847-2m-cache-1-10-ghz.html under "Advanced Technologies" at "Instruction Set Extensions", where it only lists sse4.1 and sse4.2.
Also here on wikipedia > https://en.wikipedia.org/wiki/List_of_Intel_Celeron_processors#Sandy_Bridge_based_Celerons_2

**Comment by Alex313031** [comment]
@tamajon @paulatreides-web Closing this issue.
